<a href="https://colab.research.google.com/github/lazizbekamonov/lazizbekamonov/blob/main/1_AMALIYOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **1-AMALIY VAZIFA**

## N-o'lchamli massivlar yaratish

In [1]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish

**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning.

**Funksiya yaratilishi haqida darslik:** [bog'lanma](https://www.youtube.com/watch?v=_aDyBPYAeyU&list=PLwsopmzfbOn9Lw5D7a26THpBDgAma1Sus&index=22)


In [5]:
# JAVOBNI
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  if n > 0:
        massiv = np.random.randint(0, 100, n)  # [0, 100) oralig‘ida tasodifiy butun sonlardan iborat massiv
        return massiv
  else:
        return "Massiv elementlari soni n > 0 bo'lishi kerak"

# Masalan, 10 ta elementli massiv yaratish uchun:
massiv = one_dim(10)
print(massiv)

[ 7 23 15 86 69 99 94  0 92 14]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [6]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n elementlar soni
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# massiv o'lchami
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array

_____

### Masala(2) 2-o'lchamli massivlar yaratish

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin.


In [7]:
# JAVOBNI
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    if r > 0 and c > 0:
        massiv = np.random.randint(0, 100, (r, c))  # [0, 100) oralig‘ida tasodifiy butun sonlardan iborat massiv
        return massiv
    else:
        return "Qator (r) va ustun (c) sonlari 0 dan katta bo'lishi kerak"

# Masalan, 3 qator va 4 ustundan iborat 2-o'lchamli massiv yaratish uchun:
massiv = two_dim(3, 4)
print(massiv)

[[13 40  6 24]
 [93  3 14 48]
 [12 52 12 97]]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [8]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # massiv
assert arr.shape == (3, 2), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # massiv o'lchami
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array