<a href="https://colab.research.google.com/github/lazizbekamonov/lazizbekamonov/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
print(np.__version__)
np.show_config

1.26.4


<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
import numpy as np

# Raqamli qiymatlar ro'yxati
raqamlar = [1, 2, 3, 4, 5]

# Raqamli qiymatlar ro'yxatini NumPy massiviga aylantirish
massiv = np.array(raqamlar)

# Natijani chop etish
print(massiv)

[1 2 3 4 5]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
import numpy as np

# 9 o'lchovli massiv yaratish (har bir o'lchov uchun 2 element)
massiv = np.zeros((2, 2, 2, 2, 2, 2, 2, 2, 2))

# Natijani chop etish
print(massiv)
print("Massivning o'lchovi:", massiv.shape)

[[[[[[[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]



     [[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]]




    [[[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]



     [[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]]]





   [[[[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]



     [[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]]




    [[[[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]


      [[[0. 0.]
        [0. 0.]]

       [[0. 0.]
        [0. 0.]]]]



#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [1]:
import numpy as np

# Massiv yaratish
massiv = np.array([1, 2, 3, 4, 5])

# Massiv hajmini aniqlash
hajmi = massiv.size * massiv.itemsize

print(f"Massivning xotira hajmi: {hajmi} bayt")


Massivning xotira hajmi: 40 bayt


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [10]:
import numpy as np

# add funksiyasi haqida ma'lumot olish
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [11]:
import numpy as np

# 12 o'lchamdagi nol qiymatli vektor yaratish
vektor = np.zeros(12)

# Oltinchi qiymatini 1 ga o'zgartirish
vektor[5] = 1  # Indekslar 0 dan boshlanadi, shuning uchun 5 - oltinchi element

print("Vektor:")
print(vektor)

Vektor:
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [9]:
import numpy as np

# 20 dan 59 gacha bo'lgan qiymatlar bilan vektor yaratish
vektor = np.arange(20, 60)  # 60 ni kiritmaydi

print("20 dan 59 gacha bo'lgan vektor:")
print(vektor)

20 dan 59 gacha bo'lgan vektor:
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [8]:
import numpy as np

# Vektor yaratish
vektor = np.array([1, 2, 3, 4, 5])

# Vektorni teskari o'zgartirish
teskari_vektor = vektor[::-1]

print("Asl vektor:")
print(vektor)
print("\nTeskari vektor:")
print(teskari_vektor)

Asl vektor:
[1 2 3 4 5]

Teskari vektor:
[5 4 3 2 1]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [5]:
import numpy as np

# 12 dan 20 gacha bo'lgan qiymatlarni yaratish
qiymatlar = np.arange(12, 21)

# 3x3 matritsaga o'zgartirish
matritsa = qiymatlar.reshape(3, 3)

print("3x3 matritsa:")
print(matritsa)

3x3 matritsa:
[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [7]:
import numpy as np

# Berilgan matritsa
matritsa = np.array([3, 7, 0, 0, 9, 0])

# Nolga teng bo'lmagan elementlarning indekslarini topish
nolga_teng_bolmagan_indekslar = np.nonzero(matritsa)

print("Nolga teng bo'lmagan elementlarning indekslari:")
print(nolga_teng_bolmagan_indekslar[0])  # 1D arrayda natijalar

Nolga teng bo'lmagan elementlarning indekslari:
[0 1 4]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [6]:
import numpy as np

# 2x2x2 o'lchamdagi tasodifiy qiymatlar bilan massiv yaratish
massiv = np.random.random((2, 2, 2))

print("2x2x2 o'lchamdagi tasodifiy qiymatlar bilan massiv:")
print(massiv)

2x2x2 o'lchamdagi tasodifiy qiymatlar bilan massiv:
[[[0.43458671 0.03677627]
  [0.42011649 0.03777764]]

 [[0.3105673  0.32296488]
  [0.48833004 0.3445268 ]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [4]:
import numpy as np

# 9x9 o'lchamdagi tasodifiy sonlardan iborat massiv yaratish
massiv = np.random.random((9, 9))

# Eng katta va eng kichik qiymatlarni topish
eng_kichik = np.min(massiv)
eng_katta = np.max(massiv)

print("Massiv:")
print(massiv)
print(f"\nEng kichik qiymat: {eng_kichik}")
print(f"Eng katta qiymat: {eng_katta}")

Massiv:
[[0.280584   0.91330801 0.14285807 0.1302522  0.98677946 0.31797993
  0.15767648 0.69467939 0.28671394]
 [0.74506606 0.69449795 0.98296708 0.07199649 0.95452547 0.71995604
  0.90907613 0.99147794 0.79144531]
 [0.91713777 0.33668002 0.42700222 0.93453841 0.46169138 0.71319473
  0.68710707 0.84868457 0.91668363]
 [0.94277326 0.40431403 0.48549263 0.57507609 0.36496377 0.29801365
  0.18445187 0.53659561 0.15277883]
 [0.88306087 0.95291483 0.70859047 0.84397133 0.28268806 0.01737687
  0.94786281 0.68169711 0.52092406]
 [0.06904623 0.48197882 0.62554131 0.38124141 0.22364972 0.01425118
  0.80165163 0.89849874 0.79037214]
 [0.8101794  0.87041161 0.67841124 0.40077733 0.47219308 0.1673097
  0.90917977 0.22665296 0.65156662]
 [0.20141001 0.24344753 0.24947322 0.84727916 0.22702794 0.32008747
  0.52459879 0.47261062 0.70273637]
 [0.49589354 0.80712607 0.58401566 0.08030344 0.87152132 0.70546862
  0.03070233 0.96300605 0.56390191]]

Eng kichik qiymat: 0.014251177529399528
Eng katta qiyma

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

1. 0 * np.nan
Natija: nan
Izoh: Har qanday son np.nan (Not a Number) bilan ko‘paytirilganda natija nan bo‘ladi.


2. np.nan == np.nan
Natija: False
Izoh: np.nan o‘zini o‘zi teng emas deb hisoblanadi.


3. np.inf > np.nan
Natija: False
Izoh: np.nan har qanday son bilan taqqoslanganda (np.inf ham) natija False bo‘ladi, chunki nan qiymati aniqlanmagan.


4. np.nan - np.nan
Natija: nan
Izoh: np.nan dan np.nan ni ayirganda natija ham nan bo‘ladi.


5. np.nan in set([np.nan])
Natija: True
Izoh: set ichida np.nan mavjud bo‘lsa, bu True natijani beradi, chunki set ichidagi elementlarni tekshirish np.nanning o‘ziga teng bo‘lishi bilan bog‘liq emas.


6. 0.7 == 7 * 0.1
Natija: False
Izoh: 7 * 0.1 natijasi 0.7000000000000001 bo‘ladi, bu esa 0.7 ga teng emas, shuning uchun natija False.

In [3]:
0 * np.nan            # nan
np.nan == np.nan      # False
np.inf > np.nan       # False
np.nan - np.nan       # nan
np.nan in set([np.nan])  # True
0.7 == 7 * 0.1       # False

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [2]:
import numpy as np

# 6x3 o'lchamdagi matritsa
matritsa1 = np.ones((6, 3))

# 3x4 o'lchamdagi matritsa
matritsa2 = np.ones((3, 4))

# Matritsalarni ko'paytirish
kopaytma = np.dot(matritsa1, matritsa2)

print("Matritsa1:")
print(matritsa1)
print("\nMatritsa2:")
print(matritsa2)
print("\nKo'paytma:")
print(kopaytma)

Matritsa1:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matritsa2:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Ko'paytma:
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#    javob
1. print(sum(range(5),-1))


2. from numpy import *


3. print(sum(range(5),-1))



1. print(sum(range(5), -1))

Bu kod sum funksiyasini chaqiradi va range(5) ga asoslangan yig'indini hisoblaydi. range(5) 0 dan 4 gacha bo'lgan raqamlarni (ya'ni 0, 1, 2, 3, 4) yaratadi.

Natija:

Yig'indi: 0 + 1 + 2 + 3 + 4 = 10

-1 qiymati sum funksiyasining ikkinchi argumenti sifatida kiritilgan bo'lib, bu yig'indiga qo'shiladi.


Shuning uchun natija:

10 - 1 = 9

2. from numpy import *

Bu qism NumPy kutubxonasidagi barcha funktsiyalar va o'zgaruvchilarni hozirgi muhitga import qiladi. Shuning uchun sum funksiyasi NumPy kutubxonasidan bo'ladi.

3. print(sum(range(5), -1))

Endi, NumPy kutubxonasining sum funksiyasidan foydalanilganda, natija bir oz o'zgaradi. NumPy'dagi sum funksiyasi faqat raqamlar massivlari yoki massivlari ustida ishlaydi.

Bu funktsiya, range(5) ga kiritilgan ikkita argumentni qabul qiladi: birinchisi massiv (bu yerda, range(5)), ikkinchisi esa yig'indining boshlang'ich qiymati.

range(5) NumPy tomonidan avtomatik ravishda massivga aylantiriladi, lekin sum funksiyasi xuddi shunday ishni qilmoqda.

Natija:

Yig'indi: 0 + 1 + 2 + 3 + 4 = 10

-1 qiymati yig'indiga qo'shiladi.


Natijada:

10 - 1 = 9

Yakuniy Natijalar:

Ikki print bayonoti natijalari quyidagicha bo'ladi:

9
9

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])

# Solishtirish amallarini bajarish
greater_than = a > b
greater_than_or_equal = a >= b
less_than = a < b
less_than_or_equal = a <= b

# Natijalarni chop etamiz
print("a > b:", greater_than)              # [False False]
print("a >= b:", greater_than_or_equal)    # [False False]
print("a < b:", less_than)                  # [ True  True]
print("a <= b:", less_than_or_equal)        # [ True  True]


a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
np.array(0) / np.array(0)

#Bu ifoda noldan bo'lish operatsiyasini ifodalaydi. NumPy bu holatda RuntimeWarning chiqaradi va natijada NaN (Not a Number) qiymatini beradi.

#Natija:

import numpy as np

result1 = np.array(0) / np.array(0)
print("np.array(0) / np.array(0):", result1)

#Natija: nan va ogohlantirish: RuntimeWarning: invalid value encountered in true_divide

np.array(0) // np.array(0)

#Bu ifoda noldan bo'lish operatsiyasi, ammo bu holatda // (butun bo'lish) operatsiyasi ishlatilgan. Bu ham noldan bo'lish holatini keltirib chiqaradi va natijada NaN beradi.

#Natija:

result2 = np.array(0) // np.array(0)
print("np.array(0) // np.array(0):", result2)

#Natija: nan va ogohlantirish: RuntimeWarning: invalid value encountered in floor_divide

np.array([np.nan]).astype(int).astype(float)

#Bu ifoda np.nan qiymatini int turiga o'zgartirishga harakat qiladi. np.nan qiymatini butun son sifatida olish mumkin emas, shuning uchun bu ham ValueError chiqaradi.

#Natija:

result3 = np.array([np.nan]).astype(int).astype(float)
print("np.array([np.nan]).astype(int).astype(float):", result3)

#Natija: ValueError: cannot convert float NaN to integer

#Umumiy Natijalar:

#np.array(0) / np.array(0) → nan (RuntimeWarning)

#np.array(0) // np.array(0) → nan (RuntimeWarning)

#np.array([np.nan]).astype(int).astype(float) → ValueError

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [-9.22337204e+18]


<ipython-input-26-0d412deb7464>:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-26-0d412deb7464>:10: RuntimeWarning: invalid value encountered in divide
  result1 = np.array(0) / np.array(0)
<ipython-input-26-0d412deb7464>:15: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-26-0d412deb7464>:21: RuntimeWarning: divide by zero encountered in floor_divide
  result2 = np.array(0) // np.array(0)
<ipython-input-26-0d412deb7464>:26: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)
<ipython-input-26-0d412deb7464>:32: RuntimeWarning: invalid value encountered in cast
  result3 = np.array([np.nan]).astype(int).astype(float)


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
import numpy as np

# Ikkita massiv yaratamiz
massiv_a = np.array([1, 2, 3, 4, 5, 6])
massiv_b = np.array([4, 5, 6, 7, 8, 9])

# Umumiy qiymatlarni topamiz
umumiy_qiymatlar = np.intersect1d(massiv_a, massiv_b)

# Natijalarni chop etamiz
print("Massiv A:", massiv_a)
print("Massiv B:", massiv_b)
print("Umumiy qiymatlar:", umumiy_qiymatlar)

Massiv A: [1 2 3 4 5 6]
Massiv B: [4 5 6 7 8 9]
Umumiy qiymatlar: [4 5 6]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
import numpy as np

# Tasodifiy sonlardan iborat massiv yaratamiz
massiv = np.random.uniform(-10, 10, size=10)  # -10 dan 10 gacha tasodifiy sonlar
print("Tasodifiy massiv:")
print(massiv)

# 1. % operatori yordamida
musbat_butun_mod = massiv[massiv > 0] % 1
musbat_butun_mod = (musbat_butun_mod > 0).astype(int)
print("\n% operatori yordamida musbat sonlarning butun qismi (0 yoki 1):")
print(musbat_butun_mod)

# 2. np.floor yordamida
musbat_butun_floor = np.floor(massiv[massiv > 0])
print("\nnp.floor yordamida musbat sonlarning butun qismi:")
print(musbat_butun_floor)

# 3. astype yordamida
musbat_butun_astype = massiv[massiv > 0].astype(int)
print("\nastype yordamida musbat sonlarning butun qismi:")
print(musbat_butun_astype)

# 4. np.trunc yordamida
musbat_butun_trunc = np.trunc(massiv[massiv > 0])
print("\nnp.trunc yordamida musbat sonlarning butun qismi:")
print(musbat_butun_trunc)

Tasodifiy massiv:
[ 2.52701445  7.39159312 -6.99737197 -6.3694309   7.25045717  4.11157905
 -2.03329702 -9.45857842  3.84341235  9.92366939]

% operatori yordamida musbat sonlarning butun qismi (0 yoki 1):
[1 1 1 1 1 1]

np.floor yordamida musbat sonlarning butun qismi:
[2. 7. 7. 4. 3. 9.]

astype yordamida musbat sonlarning butun qismi:
[2 7 7 4 3 9]

np.trunc yordamida musbat sonlarning butun qismi:
[2. 7. 7. 4. 3. 9.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
import numpy as np

# 0 dan 2 gacha bo'lgan qiymatlar bilan matritsa yaratamiz
matritsa = np.array([[0, 1, 2],
                      [0, 1, 2],
                      [0, 1, 2]])

# Natijalarni chop etish
print("3x3 matritsa:")
print(matritsa)

3x3 matritsa:
[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:

import numpy as np

# O'lchami 10 bo'lgan tasodifiy vektor yaratamiz
vektor = np.random.rand(10)  # 0 dan 1 gacha tasodifiy raqamlar

# Vektorni o'sish tartibida saralash
saralangan_vektor = np.sort(vektor)  # yoki vektor.sort()

# Natijalarni chop etish
print("Original vektor:", vektor)
print("O'sish tartibida saralangan vektor:", saralangan_vektor)

Original vektor: [0.54696054 0.55366259 0.15196283 0.60307877 0.46737122 0.22105846
 0.79192729 0.34600726 0.7942583  0.96553208]
O'sish tartibida saralangan vektor: [0.15196283 0.22105846 0.34600726 0.46737122 0.54696054 0.55366259
 0.60307877 0.79192729 0.7942583  0.96553208]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
import numpy as np

# Ikkita mahsulotiy massiv yaratamiz
A = np.array([1.0, 2.0, 3.0])
B = np.array([1.0, 2.0, 3.0])
C = np.array([1.0, 2.0, 3.0000001])  # B dan biroz farq qiladi

# Massivlarni tengligini tekshirish
teng_mi = np.array_equal(A, B)  # To'g'ridan-to'g'ri tenglik
yaqin_teng_mi = np.allclose(A, C)  # Toqat oralig'ida tenglik

# Natijalarni chop etish
print("A va B massivlari tengmi:", teng_mi)  # True
print("A va C massivlari yaqindan tengmi:", yaqin_teng_mi)  # True


A va B massivlari tengmi: True
A va C massivlari yaqindan tengmi: True


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
import numpy as np

# 6x3 o'lchamdagi tasodifiy matritsa
matritsa1 = np.random.rand(6, 3)

# 3x4 o'lchamdagi tasodifiy matritsa
matritsa2 = np.random.rand(3, 4)

# Matritsalarni ko'paytirish
natija = np.dot(matritsa1, matritsa2)

# Natijalarni chop etish
print("6x3 o'lchamdagi matritsa:\n", matritsa1)
print("\n3x4 o'lchamdagi matritsa:\n", matritsa2)
print("\nNatija (6x4 o'lchamdagi):\n", natija)

6x3 o'lchamdagi matritsa:
 [[0.0788513  0.0765966  0.36713286]
 [0.8837699  0.41926858 0.41313695]
 [0.59889482 0.93758488 0.62245166]
 [0.97166167 0.54555593 0.87482531]
 [0.84059377 0.56043464 0.62313579]
 [0.44990076 0.25344787 0.58926436]]

3x4 o'lchamdagi matritsa:
 [[0.25459159 0.53213192 0.49446855 0.32243088]
 [0.73087094 0.1086422  0.57275947 0.49288663]
 [0.11363315 0.17712797 0.0347532  0.67450985]]

Natija (6x4 o'lchamdagi):
 [[0.11777557 0.11531041 0.09561996 0.31081226]
 [0.57837766 0.58901054 0.69149431 0.77027152]
 [0.90845827 0.53080593 0.85477746 1.07507501]
 [0.74551702 0.73127862 0.82333145 1.17226924]
 [0.69442238 0.61856841 0.7582974  0.96757536]
 [0.3667386  0.37131689 0.38810527 0.66744758]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
import numpy as np

# Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yaratish
vektor = np.random.rand(5)  # [0, 1) oraliqda tasodifiy sonlar

# Eng katta qiymatini topish
eng_katta_idx = np.argmax(vektor)

# Eng katta qiymatini 0 ga o'zgartirish
vektor[eng_katta_idx] = 0

# Natijalarni chop etish
print("Tasodifiy vektor:", vektor)
print("Eng katta qiymat 0 ga o'zgartirildi.")

Tasodifiy vektor: [0.52230454 0.03297136 0.         0.31044288 0.90492579]
Eng katta qiymat 0 ga o'zgartirildi.


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
import numpy as np

# Bugun
bugun = np.datetime64('today', 'D')

# Kecha va ertangi kun sanalarini aniqlash
kecha = bugun - np.timedelta64(1, 'D')  # 1 kun kamaytirish
ertaga = bugun + np.timedelta64(1, 'D')  # 1 kun qo'shish

# Natijalarni chop etish
print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)


Kecha: 2024-10-21
Bugun: 2024-10-22
Ertaga: 2024-10-23


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
import numpy as np

# 2016 yil yanvar oyining birinchi va oxirgi sanalarini belgilaymiz
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')  # 1 fevralga qadar

# np.arange yordamida sanalarni yaratamiz
january_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

# Natijani chop etamiz
print("2016 yil yanvar oyiga to'g'ri keladigan sanalar:")
print(january_dates)

2016 yil yanvar oyiga to'g'ri keladigan sanalar:
['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
print("Asl massiv:")
print(massiv)

# 1. Usul: % (modulus) yordamida butun sonlarni olib tashlash
natijaviy_massiv1 = massiv[massiv % 1 != 0]  # Butun son bo'lmaganlarni tanlash
print("\n1-usul (modulus):")
print(natijaviy_massiv1)

# 2. Usul: np.floor yordamida butun sonlarni olib tashlash
natijaviy_massiv2 = massiv[massiv != np.floor(massiv)]  # Butun son bo'lmaganlarni tanlash
print("\n2-usul (np.floor):")
print(natijaviy_massiv2)

# 3. Usul: astype yordamida butun sonlarni olib tashlash
natijaviy_massiv3 = massiv[massiv.astype(int) != massiv]  # Butun son bo'lmaganlarni tanlash
print("\n3-usul (astype):")
print(natijaviy_massiv3)

# 4. Usul: np.trunc yordamida butun sonlarni olib tashlash
natijaviy_massiv4 = massiv[massiv != np.trunc(massiv)]  # Butun son bo'lmaganlarni tanlash
print("\n4-usul (np.trunc):")
print(natijaviy_massiv4)

Asl massiv:
[1 2 2 3 4 4 4 5 5]

1-usul (modulus):
[]

2-usul (np.floor):
[]

3-usul (astype):
[]

4-usul (np.trunc):
[]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
import numpy as np

# Ixtiyoriy kichik massivlar yaratamiz
massiv1 = np.array([1, 2, 3])
massiv2 = np.array([4, 5, 6])
massiv3 = np.array([7, 8, 9])

# Massivlarni ro'yxatga joylashtirish
massivlar = [massiv1, massiv2, massiv3]

# Har bir massiv uchun yig'indini hisoblash
for i, m in enumerate(massivlar, start=1):
    yigindi = np.add.reduce(m)  # Yig'indini hisoblash
    print(f"Massiv {i}: {m}, Yig'indi: {yigindi}")

Massiv 1: [1 2 3], Yig'indi: 6
Massiv 2: [4 5 6], Yig'indi: 15
Massiv 3: [7 8 9], Yig'indi: 24


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
import numpy as np

# Berilgan massiv
vektor = np.array([1, 2, 3, 4, 5])

# Har bir qiymatdan keyin 3 ta nol qo'shish
yangi_massiv = np.zeros((len(vektor) * 4,), dtype=int)  # Yangidan massiv yaratish
yangi_massiv[::4] = vektor  # Har to'rtinchi elementga vektor qiymatini qo'shish

# Natijani chop etish
print("Yangi massiv:")
print(yangi_massiv)

Yangi massiv:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
import numpy as np

# Berilgan massiv
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Massivning o'lchovlari
n = 4  # Har bir ichki massivda qancha element bo'lishi
m = len(a) - n + 1  # Yangilangan o'lchovlar

# as_strided yordamida yangi massivni yaratish
b = np.lib.stride_tricks.as_strided(a, shape=(m, n), strides=(a.strides[0], a.strides[0]))

# Natijani chop etish
print("b massiv:")
print(b)

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
import numpy as np

# Ixtiyoriy sonlardan tashkil topgan massiv
massiv = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5])

# O'xshash qiymatlarni hisoblash
uxshash_qiymatlar = np.bincount(massiv)

# Eng ko'p uchraydigan qiymatni topish
eng_kop_uchraydigan_qiymat = np.argmax(uxshash_qiymatlar)

# Natijalarni chop etish
print("Massiv:", massiv)
print("Eng ko'p uchraydigan qiymat:", eng_kop_uchraydigan_qiymat)
print("Uchirish soni:", uxshash_qiymatlar[eng_kop_uchraydigan_qiymat])

Massiv: [1 2 2 3 4 4 4 5 5]
Eng ko'p uchraydigan qiymat: 4
Uchirish soni: 3


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

Savol: NumPy kutubxonasida massivlarni birlashtirish uchun qanday funksiyalar mavjud?

Javob: NumPy kutubxonasida massivlarni birlashtirish uchun bir nechta funksiyalar mavjud. Ular orasida eng ko'p ishlatiladiganlari:

1. np.concatenate(): Bu funksiya bir nechta massivlarni belgilangan o'lcham bo'yicha birlashtiradi. Masalan:

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
birlashtirilgan = np.concatenate((a, b))
print(birlashtirilgan)  # Natija: [1 2 3 4 5 6]

[1 2 3 4 5 6]


2. np.vstack(): Bu funksiya ikki yoki undan ortiq 1D massivlarni vertikal ravishda birlashtiradi. Masalan:

In [13]:
import numpy as np
c = np.array([[1, 2, 3]])
d = np.array([[4, 5, 6]])
vertikal_birlashtirilgan = np.vstack((c, d))
print(vertikal_birlashtirilgan)
# Natija: [[1 2 3]
#          [4 5 6]]

[[1 2 3]
 [4 5 6]]


3. np.hstack(): Bu funksiya ikki yoki undan ortiq 1D massivlarni gorizontal ravishda birlashtiradi. Masalan:

In [14]:
import numpy as np
e = np.array([[1], [2], [3]])
f = np.array([[4], [5], [6]])
gorizontal_birlashtirilgan = np.hstack((e, f))
print(gorizontal_birlashtirilgan)
# Natija: [[1 4]
#          [2 5]
#          [3 6]]

[[1 4]
 [2 5]
 [3 6]]


4. np.stack(): Bu funksiya massivlarni yangi o'lchamda birlashtiradi. Masalan:

In [15]:
import numpy as np
g = np.array([1, 2, 3])
h = np.array([4, 5, 6])
stacked = np.stack((g, h), axis=0)  # 0 o'lcham bo'yicha birlashtirish
print(stacked)
# Natija: [[1 2 3]
#          [4 5 6]]

[[1 2 3]
 [4 5 6]]
