<a href="https://colab.research.google.com/github/lazizbekamonov/lazizbekamonov/blob/main/NumpyAssign_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **1-AMALIY VAZIFA**

## N-o'lchamli massivlar yaratish

In [1]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish

**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning.

**Funksiya yaratilishi haqida darslik:** [bog'lanma](https://www.youtube.com/watch?v=_aDyBPYAeyU&list=PLwsopmzfbOn9Lw5D7a26THpBDgAma1Sus&index=22)


In [2]:
# JAVOBNI SHU YERGA YOZING
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  return np.array(np.random.randint(0, n, size=n))

arr=one_dim(7)
print(arr)

[0 6 4 2 0 2 2]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [3]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n elementlar soni
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# massiv o'lchami
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array

_____

### Masala(2) 2-o'lchamli massivlar yaratish

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin.


In [4]:
# JAVOBNI SHU YERGA YOZING
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    return np.random.randint(1, 101, size=(r, c))
arr1=np.array(two_dim(7, 8))
print(arr1)

[[ 86  95  69  24  11  84  11  77]
 [ 55   9  35  57  29  77  27  14]
 [ 86  78  31  43  19  72  85  93]
 [ 74  67  58  81  76  57  68  75]
 [ 13  65  37  23  20  41  21  47]
 [ 10 100  54  80  47  34  83  11]
 [ 17  43  21  62  13  31  96  97]]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [5]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # massiv
assert arr.shape == (3, 2), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # massiv o'lchami
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array